#
# Copyright 2026 Shiz <hi@shiz.me>
#
# This is free software, licensed under the Apache License, Version 2.0

include $(TOPDIR)/rules.mk

PKG_LICENSE:=Apache-2.0
PKG_MAINTAINER:=Shiz <hi@shiz.me>

LUCI_TITLE:=LuCI Support for GPIO switches
LUCI_DEPENDS:=+luci-base

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
